version: "2"
services:
  dfwfw:
    build:
      context: ./dfwfw
    volumes:
      - /home/docker/dfwfw.conf:/etc/dfwfw.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/containers:/var/lib/docker/containers
    network_mode: host
    pid: host
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    restart: always
